pub enum InputMode {
    Normal,
    Search,
    SortBy,
    Langage,
    Difficulty,
    Tags,
}

pub enum Difficulty {
    OneKyu, // hardest
    TwoKyu,
    ThreeKyu,
    FourKyu,
    FiveKyu,
    SixKyu,
    SevenKyu,
    EightKyu, // Easiest

    Empty,
}

impl Difficulty {
    pub fn to_string(&self) -> String {
        match self {
            Difficulty::OneKyu => "1 kyu".to_string(),
            Difficulty::TwoKyu => "2 kyu".to_string(),
            Difficulty::ThreeKyu => "3 kyu".to_string(),
            Difficulty::FourKyu => "4 kyu".to_string(),
            Difficulty::FiveKyu => "5 kyu".to_string(),
            Difficulty::SixKyu => "6 kyu".to_string(),
            Difficulty::SevenKyu => "7 kyu".to_string(),
            Difficulty::EightKyu => "8 kyu".to_string(),
            Difficulty::Empty => "Select ranks".to_string(),
        }
    }
}

pub enum SortBy {
    Newest,
    Oldest,
    Popularity,
    PositiveFeedback,
    MostCompleted,
    LeastCompleted,
    RecentlyPublished,
    Hardest,
    Easiest,
    Name,
    LowSatisfaction,
}

pub enum Langage {
    All,
    MyLanguages,
    Agda,
    BF,
    C,
    CFML,
    Clojure,
    COBOL,
    CoffeeScript,
    CommonLisp,
    Coq,
    Cpp,
    Crystal,
    Csharp,
    D,
    Dart,
    Elixir,
    Elm,
    Erlang,
    Factor,
    Forth,
    Fortran,
    Fsharp,
    Go,
    Groovy,
    Haskell,
    Haxe,
    Idris,
    Java,
    JavaScript,
    Julia,
    Kotlin,
    Calculus,
    Lean,
    Lua,
    NASM,
    Nim,
    ObjectiveC,
    OCaml,
    Pascal,
    Perl,
    PHP,
    PowerShell,
    Prolog,
    PureScript,
    Python,
    R,
    Racket,
    Raku,
    Reason,
    RISCV,
    Ruby,
    Rust,
    Scala,
    Shell,
    Solidity,
    SQL,
    Swift,
    TypeScript,
    VB,
}

pub enum Tags {
    Empty,

    ASCIIArt,
    Algebra,
    Algorithms,
    Angular,
    Arrays11,
    ArtificialIntelligence,
    Asynchronous,
    Backend,
    BigIntegers,
    Binary,
    BinarySearchTrees,
    BinaryTrees,
    Bits,
    CellularAutomata,
    Ciphers,
    Combinatorics,
    Compilers,
    Concurrency,
    Cryptography,
    DataFrames,
    DataScience,
    DataStructures,
    Databases,
    DateTime,
    Debugging,
    Decorator,
    DesignPatterns,
    DiscreteMathematics,
    DomainSpecificLanguages,
    DynamicProgramming,
    EsotericLanguages,
    EventHandling,
    Express,
    Filtering,
    Flask,
    FunctionalProgramming,
    Fundamentals,
    GameSolvers,
    Games,
    GeneticAlgorithms,
    Geometry,
    GraphTheory,
    Graphics,
    Graphs,
    Heaps,
    ImageProcessing,
    Interpreters,
    Iterators,
    JSON,
    LanguageFeatures,
    LinearAlgebra,
    LinkedLists,
    Lists,
    Logic,
    LogicProgramming,
    MachineLearning,
    Macros,
    Mathematics,
    Matrix,
    Memoization,
    MetaProgramming,
    Monads,
    MongoDB,
    Networks,
    NeuralNetworks,
    NumPy,
    NumberTheory,
    ObjectOrientedProgramming,
    Parsing,
    Performance,
    Permutations,
    Physics,
    PriorityQueues,
    Probability,
    Promises,
    Puzzles,
    Queues,
    React,
    ReactiveProgramming,
    Recursion,
    Refactoring,
    Reflection,
    RegularExpressions,
    Restricted,
    ReverseEngineering,
    Riddles,
    RxJS,
    SQL,
    Scheduling,
    Searching,
    Security,
    SetTheory,
    Sets,
    Simulation,
    Singleton,
    Sorting,
    Stacks,
    StateMachines,
    Statistics,
    Streams,
    Strings,
    TheoremProving,
    Threads,
    Trees,
    Tutorials,
    Unicode,
    WebScraping,
    Web,
}

pub struct Kata {
    pub id: String,
    pub name: String,
    pub url: String,
    pub category: String,
    pub desc: String,
    pub difficulty: Difficulty,
    pub attempts: usize,
    pub completed: usize,
    pub created_at: String,
}

pub struct CodewarsCLI {
    pub mode: InputMode,
    pub search_result: Vec<Kata>,
    // fields
    pub search_field: String,
    pub sortby_field: SortBy,
    pub langage_field: Langage,
    pub difficulty_field: Difficulty,
    pub tag_field: Tags,
}
